<!DOCTYPE html>
<html>

<head>

</head>

<body>
    <input id="input" />
    <div id="div"></div>
    <script>
        class MyPromise {

            constructor(fn) {
                this.doneList = [];
                this.failList = [];
                this.catchCb = function () { }

                setTimeout(() => {
                    try {
                        fn(this.resolve.bind(this), this.reject.bind(this));
                    } catch (e) {
                        this.catchCb(e);
                    }
                }, 0)
            }
            // 将 .then里的第一个参数加入到成功队列
            done(success) {
                if (typeof success === "function") {
                    this.doneList.push(success)
                } else {
                    throw new Error("传入success的参数必须为function！");
                }
                return this;
            }
            // 将 .then里的第二个参数加入到失败队列
            fail(fail) {
                if (typeof fail === "function") {
                    this.failList.push(fail)
                } else {
                    throw new Error("传入fail的参数为必须为function！");
                }
                return this;
            }
            // 成功时，遍历成功队列，执行里面的所有函数
            resolve(res) {
                console.log('------>>>>', res)
                this.doneList.forEach(fn => {
                    fn(res);
                    this.doneList.shift();
                })
            }
            // 成功时，遍历失败队列，执行里面的所有函数
            reject(err) {
                this.failList.forEach(fn => {
                    fn(err);
                    this.failList.shift();
                })
            }
            // 将 .then里的第一、二个参数分别加入到成功队列、失败队列
            then(success, fail) {
                this.done(success || function () { });
                this.fail(fail || function () { });
                return this;
            }
            // 程序出现异常时执行的函数
            catch(errFn) {
                if (typeof errFn !== "function") throw new Error("catch传入的参数必须为function");
                this.catchCb = errFn;
            }

        }

        // new MyPromise((resolve, reject) => {
        //     resolve(2)
        // }).then(res => {
        //     console.log('------then', res)
        // })

        
    </script>
</body>

</html>